Impl users comments
Distributed-EPFL/at2-web pull request #16
Opened 2021-11-30 17:02 UTC by tharvik

* store user's keys in local storage
* improve dark mode (you can set variable in CSS for material!)
* add much text, either review it direclty or comment on the cryptpad
* use 💶 instead of ¤

2021-12-01 10:00 UTC, ineiti requested changes

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/new_account.rs
> +                It will automatically be credited with a certain amount of
```suggestion
                It will automatically be credited with a fixed amount of
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/new_account.rs
> +                This account will be stored in your browser, so if you
```suggestion
                This account is stored in your browser, so if you
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/speedtest.rs
> +                a more realistic use case.
... and means that the TPS measured here is below the speed reported in the paper.

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                You can send asset with it, see other users on the network
```suggestion
                You can send assets with it, see other users on the network
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                and Etherium by a ~10x factor.
```suggestion
                and Etherium by a factor of 10.
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                to validate transactions before checking theses with every other
```suggestion
                to validate transactions before checking them with every other
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                As the transaction time is so short and that it can run in a
```suggestion
                As the transaction time is so short and because it can run in a
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                browser, one can imagine using it directly as a mean of
```suggestion
                browser, one can imagine using it directly as a means of
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                payment, having a little \"pay with AT2\" next to the credit
```suggestion
                payment, having a little button \"pay with AT2\" next to the credit
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                Or you can use directly AT2 as a mean of communication, an
```suggestion
                Or you can use directly AT2 as a means of communication, an
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/summary.rs
> +                Most blockchains are still using this global consensus method,
```suggestion
                Most blockchains are still using the global consensus method,
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                being order of magnitudes faster and consuming much less
```suggestion
                being orders of magnitudes faster and consuming much less
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                It achieves such speed by avoiding to sync a common state,
```suggestion
                It achieves such speed by avoiding to synchronize a common state,
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                correct ordering.
```suggestion
                happening, not when the whole network agrees on what the
                correct ordering is.
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                First, you will first create an account that will be credited
```suggestion
                First, you will create an account that will be credited
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                with some initial assets. You will then use it to send money
```suggestion
                with some initial assets. You can then use it to send money
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                To show that indeed AT2 is blazing fast, the last part is a
```suggestion
                To show that indeed AT2 is blazingly fast, the last part is a
```

2021-12-01 10:00 UTC, ineiti commented on web/src/pages/welcome.rs
> +                speed test where you will send as many transactions as you
```suggestion
                speed test where you can send as many transactions as you
```

2021-12-01 12:02 UTC, tharvik commented on web/src/pages/summary.rs
> +                Or you can use directly AT2 as a mean of communication, an
so weird, it still takes an "s" even when singular..

2021-12-01 12:06 UTC, tharvik commented
@ineiti thanks for the big text review :)

2021-12-02 09:11 UTC, ineiti approved these changes

2021-12-02 10:15 UTC, merged